version: '3'
services:
  dnsmasq:
    image: kimoftedal/docker-dnsmasq
    container_name: dnsmasq
    environment:
     - HTTP_USER=foo
     - HTTP_PASS=bar
    ports:
        - "53:53/udp"
        - "5380:5380"
        - "8080:8080"
    restart: always
